vich_uploader:
    db_driver: orm

    mappings:
        service_images:
            uri_prefix: /uploads/imageservices
            upload_destination: '%kernel.project_dir%/public//uploads/imageservices'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true