#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /api/login
    methods: ['POST']
gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
getuserMango:
    path: /clients/{id}/{mangopayid}/card
    methods: ['POST']
    defaults:
        _controller: App\Controller\ClientController::postCardInfos
        _api_resource_class: App\Entity\Client
        _api_item_operation_name: getuserMango